### ISSUE TITLE
oq é issues?

### ISSUE THREAD

**Issue by jeowf** [MatheusJoaan/Tenacious-Trash#1]
testando meu poder de adm sei la....

**Comment by TiagoLisboa** [comment]
Issues é tipo as tarefas

**Comment by TiagoLisboa** [comment]
Eu acho, mas traduzindo quer dizer "problemas". Mas parece que a galera usa para dividir o trabalho em partes, tipo: iss01, iss02, issXX

**Comment by jeowf** [comment]
Acho que entendi. No caso, vai funfar tipo um fórum entre os participantes?

**Comment by TiagoLisboa** [comment]
sim
